---
- name: Create mutt configuration directory
  file:
    path: "~/.config/mutt"
    state: directory

- name: Configure mutt
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "~/.config/mutt/{{ item }}"
    state: link
  loop:
    - freitafr.muttrc
    - muttrc
    - solarized.muttrc

- name: Configure mailcap
  file:
    src: "{{ role_path }}/files/.mailcap"
    dest: "~/.mailcap"
    state: link
