[project]
name = "dotfiles"
description = "Using Ansible to setup my local machine"
dynamic = ["version"]
requires-python = ">=3.12"
dependencies = [
    "ansible>=11.0.0",
]

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"
[tool.setuptools]
packages = []
