- hosts: localhost
  roles:
    - system
    - alacritty
    - bin
    - git
    - fuzzel
    - dunst
    - swappy
    - hypr
    - vdirsyncer
    - khal
    - waybar
    - mail
    - nvim
    - tmux
    - zsh
    - firefox
