- hosts: localhost
  roles:
    - system
    - foot
    - bin
    - git
    - fuzzel
    - dunst
    - swappy
    - hypr
    - xdg
    - ashell
    - vdirsyncer
    - khal
    - mail
    - nvim
    - tmux
    - zsh
    - postgresql
    - firefox
