[colors.bright]
black = "0x586e75"
blue = "0x0087ff"
cyan = "0x00afaf"
green = "0x5f8700"
magenta = "0xaf005f"
red = "0xd70000"
white = "0xffffd7"
yellow = "0xaf8700"

[colors.normal]
black = "0x1b4652"
blue = "0x268bd2"
cyan = "0x2aa1c8"
green = "0x859900"
magenta = "0xd33682"
red = "0xdc322f"
white = "0xeee8d5"
yellow = "0xb58900"

[colors.primary]
background = "0x002b36"
foreground = "0x839496"

[font]
size = 20

[font.normal]
family = "Inconsolata Nerd Font"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[shell]
program = "/usr/bin/tmux"
args = ["new-session", "-A", "-s", "dev"]

[window]
decorations = "None"
startup_mode = "Maximized"
opacity = 0.9
