---
- name: Create configuration directory
  file:
    path: ~/.config/vdirsyncer
    state: directory

- name: Configure vdirsyncer
  file:
    src: "{{ role_path }}/files/config"
    dest: ~/.config/vdirsyncer/config
    state: link

- name: Activate vdirsyncer
  systemd_service:
    name: vdirsyncer.timer
    scope: user
    enabled: yes
    state: started
