---
- name: Install dependencies
  become: yes
  pacman:
    name:
      - aerc
      - alacritty
      - blueman
      - brightnessctl
      - chromium
      - cliphist
      - ctags
      - dbus-broker
      - deepin-icon-theme
      - direnv
      - dunst
      - evince
      - file-roller
      - firefox-developer-edition
      - fuzzel
      - fzf
      - git
      - git-absorb
      - git-delta
      - github-cli
      - grim
      - grml-zsh-config
      - hunspell
      - hunspell-fr
      - hypridle
      - hyprland
      - hyprlock
      - hyprpaper
      - hyprpolkitagent
      - hyprsunset
      - khal
      - isync
      - loupe
      - jq
      - mailcap
      - man-db
      - man-pages
      - mpv
      - msmtp
      - nautilus
      - ncdu
      - nextcloud-client
      - neovim
      - nerd-fonts
      - network-manager-applet
      - notmuch-runtime
      - openssh
      - otf-font-awesome  # Waybar icons
      - p7zip
      - pacman-contrib
      - pavucontrol
      - pipewire
      - pipewire-pulse
      - pwgen
      - python-aiohttp-oauthlib  # Google calendars sync
      - python-psutil  # Used by ansible to manage dconf.
      - python-pynvim
      - pyright
      - qt5-wayland
      - qt6-wayland
      - qt6ct  # Wayland theme for Qt apps.
      - reflector
      - ripgrep
      - ruff-lsp
      - rsync
      - signal-desktop
      - simple-scan
      - slurp
      - swappy
      - telegram-desktop
      - tmux
      - tree-sitter
      - tree-sitter-cli
      - tuned
      - udiskie
      - unzip
      - uv
      - uwsm
      - vdirsyncer
      - vscode-html-languageserver
      - vscode-json-languageserver
      - xdg-desktop-portal-gtk  # https://wiki.archlinux.org/title/Dark_mode_switching#gsettings
      - xdg-desktop-portal-hyprland
      - w3m  # Weak dependency for aerc default text/html
      - waybar
      - wf-recorder
      - wireguard-tools
      - wl-clipboard
      - zsh
      - zsh-syntax-highlighting

- name: Make systemd environment.d
  file:
    path: ~/.config/environment.d
    state: directory

- name: Enable SSH agent
  systemd_service:
    name: ssh-agent
    scope: user
    enabled: yes

- name: Link to the SSH agent
  copy:
    content: SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket
    dest: ~/.config/environment.d/ssh_agent.conf

- name: Set restrictive umask
  become: yes
  lineinfile:
    line: UMASK		077
    path: /etc/login.defs
    regexp: '^UMASK\s+[0-9]{3}$'

- name: Enable tuned
  become: yes
  systemd_service:
    name: tuned
    enabled: yes
    state: started

- import_tasks: yay.yaml

- name: Enable wayland for Chromium
  copy:
    content: --ozone-platform-hint=auto
    dest: ~/.config/chromium-flags.conf
