---
- name: Install dependencies
  become: yes
  pacman:
    name:
      - aerc
      - alacritty
      - ctags
      - direnv
      - firefox-developer-edition
      - flameshot
      - fzf
      - git
      - git-absorb
      - git-delta
      - github-cli
      - grml-zsh-config
      - hunspell
      - hunspell-fr
      - isync
      - jq
      - kde-applications-meta
      - mailcap
      - man-db
      - man-pages
      - msmtp
      - ncdu
      - nextcloud-client
      - neovim
      - nerd-fonts
      - notmuch-runtime
      - openssh
      - pacman-contrib
      - plasma-meta
      - pwgen
      - python-pynvim
      - pyright
      - reflector
      - ripgrep
      - ruff-lsp
      - rsync
      - signal-desktop
      - tmux
      - tree-sitter
      - tree-sitter-cli
      - tuned
      - uv
      - vscode-html-languageserver
      - vscode-json-languageserver
      - w3m
      - wireguard-tools
      - zsh
      - zsh-syntax-highlighting

- name: Make systemd environment.d
  file:
    path: ~/.config/environment.d
    state: directory

- name: Enable SSH agent
  systemd_service:
    name: ssh-agent
    scope: user
    enabled: yes

- name: Link to the SSH agent
  copy:
    content: SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket
    dest: ~/.config/environment.d/ssh_agent.conf

- name: Set restrictive umask
  become: yes
  lineinfile:
    line: UMASK		077
    path: /etc/login.defs
    regexp: '^UMASK\s+[0-9]{3}$'

- name: Enable tuned
  become: yes
  systemd_service:
    name: tuned
    enabled: yes
    state: started

- import_tasks: yay.yaml
