---
- name: Install dependencies
  become: yes
  pacman:
    name:
      - aerc
      - alacritty
      - blueman
      - bluez
      - brightnessctl
      - chromium
      - cliphist
      - ctags
      - dbus-broker
      - deepin-gtk-theme
      - deepin-icon-theme
      - direnv
      - dunst
      - evince
      - file-roller
      - firefox-developer-edition
      - fuzzel
      - fzf
      - git
      - git-delta
      - git-zsh-completion
      - github-cli
      - greetd-agreety
      - grim
      - grml-zsh-config
      - hunspell
      - hunspell-fr
      - hypridle
      - hyprland
      - hyprlock
      - hyprpaper
      - hyprpolkitagent
      - hyprsunset
      - keepassxc
      - khal
      - iputils
      - isync
      - loupe
      - jq
      - mailcap
      - man-db
      - man-pages
      - mpv
      - msmtp
      - nautilus
      - ncdu
      - nextcloud-client
      - neovim
      - network-manager-applet
      - notmuch-runtime
      - noto-fonts-emoji
      - openssh
      - otf-font-awesome  # Waybar icons
      - p7zip
      - pacman-contrib
      - pavucontrol
      - pipewire
      - pipewire-pulse
      - pwgen
      - python-aiohttp-oauthlib  # Google calendars sync
      - python-psutil  # Used by ansible to manage dconf.
      - python-pynvim
      - pyright
      - qt5-wayland
      - qt6-wayland
      - qt5ct  # Wayland theme for Qt5 apps.
      - qt6ct  # Wayland theme for Qt6 apps.
      - reflector
      - ripgrep
      - rsync
      - signal-desktop
      - simple-scan
      - slurp
      - swappy
      - telegram-desktop
      - tmux
      - tree-sitter
      - tree-sitter-cli
      - ttf-fira-code-nerd
      - tuned
      - udiskie
      - unzip
      - uv
      - uwsm
      - vdirsyncer
      - xdg-desktop-portal-gtk  # https://wiki.archlinux.org/title/Dark_mode_switching#gsettings
      - xdg-desktop-portal-hyprland
      - w3m  # Weak dependency for aerc default text/html
      - waybar
      - wf-recorder
      - wireguard-tools
      - wl-clipboard
      - zsh
      - zsh-syntax-highlighting

- name: Create systemd-resolved drop-in configuration directory
  become: yes
  file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    mode: 0755

- name: Configure systemd-resolved
  become: yes
  copy:
    content: |
      [Resolve]
      DNS=2620:fe::fe 2620:fe::9 9.9.9.9 1.1.1.1
      DNSSEC=allow-downgrade
    dest: /etc/systemd/resolved.conf.d/freitafr.conf
    mode: 0644
    owner: root
    group: root

- name: Enable systemd-resolved
  become: yes
  systemd_service:
    name: systemd-resolved
    state: started
    enabled: yes

- name: Replace resolv.conf with systemd-resolved stub
  become: yes
  file:
    src: ../run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: yes

- name: Configure reflector
  become: yes
  lineinfile:
    path: /etc/xdg/reflector/reflector.conf
    regexp: '^--country '
    line: --country France

- name: Enable reflector timer
  become: yes
  systemd_service:
    name: reflector.timer
    state: started
    enabled: yes

- name: Make systemd environment.d
  file:
    path: ~/.config/environment.d
    state: directory

- name: Enable SSH agent
  systemd_service:
    name: ssh-agent
    scope: user
    enabled: yes

- name: Link to the SSH agent
  copy:
    content: SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket
    dest: ~/.config/environment.d/ssh_agent.conf

- name: Set restrictive umask
  become: yes
  lineinfile:
    line: UMASK		077
    path: /etc/login.defs
    regexp: '^UMASK\s+[0-9]{3}$'

- name: Enable tuned
  become: yes
  systemd_service:
    name: tuned
    enabled: yes
    state: started

- import_tasks: yay.yaml

- name: Enable wayland for Chromium
  copy:
    content: --ozone-platform-hint=auto
    dest: ~/.config/chromium-flags.conf

- name: Create logind.conf.d/
  become: yes
  file:
    path: /etc/systemd/logind.conf.d/
    state: directory
    mode: 0755

- name: Setup logind.conf
  become: yes
  copy:
    src: 00_prefs.conf
    dest: /etc/systemd/logind.conf.d/
    mode: 0644

- name: Start NetworkManager
  become: yes
  systemd_service:
    name: NetworkManager
    state: started
    enabled: yes
