---
- name: Clone yay repository
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: ~/.cache/yay
    update: no
  register: yay_clone

- name: Install go to build yay
  become: yes
  pacman:
    name: go
  when: yay_clone.changed

- name: Build yay
  command:
    cmd: makepkg --nosign
    chdir: ~/.cache/yay
  when: yay_clone.changed

- name: Install yay
  become: yes
  pacman:
    name: "{{ item }}"
  with_fileglob:
    - ~/.cache/yay/yay-*.pkg.tar.zst
  when: yay_clone.changed

- name: Remove go
  become: yes
  pacman:
    name: go
    state: absent
  when: yay_clone.changed

- name: Allow upgrading packages without password
  become: yes
  copy:
    content: "%wheel ALL=(ALL:ALL) NOPASSWD: ^/usr/bin/yay -Syu$"
    dest: /etc/sudoers.d/upgrade-without-password
    mode: 0400
