[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 20

[font.normal]
family = "Inconsolata Nerd Font"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[terminal.shell]
program = "/usr/bin/tmux"
args = ["new-session", "-A", "-s", "dev"]

[window]
decorations = "None"
startup_mode = "Maximized"
opacity = 0.9
