#!/bin/sh
# Many thanks to Tim Pope, http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html
set -e
PATH="/url/local/bin:$PATH"
dir="`git rev-parse --show-toplevel`"
trap 'rm -rf "$dir/$$.tags"' EXIT
git ls-files | \
    ctags --tag-relative=yes -L - -f"$dir/$$.tags" --languages=-sql
find venv/lib/python3.7/site-packages -type f -name "*.py" | \
    ctags --tag-relative=yes --append=yes -L - -f"$dir/$$.tags"
mv "$dir/$$.tags" "$dir/tags"
