hl.on("hyprland.start", function()
	local uwsm = require("config.utils").uwsm
	hl.exec_cmd(uwsm("ashell"))
	hl.exec_cmd(uwsm("hypridle"))
	hl.exec_cmd(uwsm("hyprsunset"))
	hl.exec_cmd(uwsm("udiskie --no-automount --smart-tray"))
	hl.exec_cmd(uwsm("dunst"))
	hl.exec_cmd(uwsm("nextcloud --background"))
	hl.exec_cmd(uwsm("wl-paste --watch cliphist -max-items 20 store"))

	hl.exec_cmd(uwsm("foot"), { workspace = "1 silent" })
	hl.exec_cmd(uwsm("firefox-developer-edition"), { workspace = "2 silent" })
	hl.exec_cmd(uwsm("Telegram"), { workspace = "4 silent" })
	hl.exec_cmd(uwsm("signal-desktop"), { workspace = "4 silent" })
	hl.exec_cmd(uwsm("keepassxc"), { workspace = "10 silent" })

	hl.exec_cmd(uwsm("gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'"))
	hl.exec_cmd(uwsm("gsettings set org.gnome.desktop.interface gtk-theme 'deepin-dark'"))
	hl.exec_cmd(uwsm("gsettings set org.gnome.desktop.interface icon-theme 'bloom'"))
	hl.exec_cmd(uwsm("gsettings set org.gnome.desktop.interface font-antialiasing 'rgba'"))
	hl.exec_cmd(uwsm("gsettings set org.gnome.desktop.interface font-hinting 'full'"))
	hl.exec_cmd(uwsm("gsettings set org.gnome.desktop.interface font-name 'Fira Code'"))
	hl.exec_cmd(uwsm("gsettings set org.gnome.nm-applet disable-connected-notifications 'true'"))
	hl.exec_cmd(uwsm("gsettings set org.gnome.nm-applet suppress-wireless-networks-available 'true'"))
end)
