hl.on("hyprland.start", function()
	local uwsm = require("config.utils").uwsm
	hl.exec_cmd(uwsm("ashell"))
	hl.exec_cmd(uwsm("hypridle"))
	hl.exec_cmd(uwsm("hyprsunset"))
	hl.exec_cmd(uwsm("udiskie --no-automount --smart-tray"))
	hl.exec_cmd(uwsm("nextcloud --background"))
	hl.exec_cmd(uwsm("wl-paste --watch cliphist -max-items 20 store"))

	hl.exec_cmd(uwsm("foot"), { workspace = "1 silent" })
	hl.exec_cmd(uwsm("firefox-developer-edition"), { workspace = "2 silent" })
	hl.exec_cmd(uwsm("Telegram"), { workspace = "4 silent" })
	hl.exec_cmd(uwsm("signal-desktop"), { workspace = "4 silent" })
	hl.exec_cmd(uwsm("keepassxc"), { workspace = "10 silent" })
end)
