---
- name: Ensure .config exists
  file:
    path: ~/.config
    state: directory

- name: Configure alacritty
  file:
    src: "{{ role_path }}/files/alacritty.toml"
    dest: ~/.config/alacritty.toml
    state: link
